### ISSUE TITLE
geotix not loading into IE11

### ISSUE THREAD

**Issue by ascii-girl** [tpflueger/GeoTix#12]
Geotix is not loading into IE11. Do you have a fix for that?

**Comment by tpflueger** [comment]
Hi @ascii-girl, this project was for a class assignment and no active development has been done on it in the past 3 years. I do not plan on doing any development work, but if you would like to fix it, any PRs are welcome.

**Comment by ascii-girl** [comment]
Thanks. I'll see what I can do.
